name: 'ShopZada'

config-version: 2
version: '0.1'

profile: 'ShopZada'

model-paths: ["models"]
seed-paths: ["seeds"]

require-dbt-version: [">=1.0.0", "<2.0.0"]

seeds: 
  +docs:
    node_color: '#cd7f32'

models:
  ShopZada:
    materialized: table
    staging:
      materialized: table
      +docs:
        node_color: 'silver'
    +docs:
      node_color: 'gold'
